stages:
    - build

fedora:28:
  image: fedora:28
  stage: build
  before_script:
      - dnf install -y meson gcc glib2-devel libsoup-devel speex-devel libxml2-devel libtiff-devel spandsp-devel json-glib-devel libsndfile-devel gupnp-devel isdn4k-utils-devel gstreamer-plugins-base-devel libsecret-devel gettext gdk-pixbuf2-devel
  script:
      - meson _build .
      - cd _build
      - ninja test
